package com.lingyuecm.service;

import com.lingyuecm.dto.AccessTokenDto;
import com.lingyuecm.dto.AccessTokenVerificationDto;

public interface JwtService {
    /**
     * Generates the token used for logging in
     * @param loginCaptchaId The key to the captcha saved in Redis
     * @return The token carrying the key
     */
    String generateLoginToken(String loginCaptchaId);

    /**
     * Parses the token generated by @{@link #generateLoginToken(String)} to get the key to the captcha
     * @param token The token provided by the user
     * @return The key to the captcha
     */
    String parseLoginToken(String token);

    /**
     * Generates the access token for the user
     * @param userId The primary key to the user in the database
     * @return The access token generated with some additional information
     * @see AccessTokenDto
     */
    AccessTokenDto generateAccessToken(Long userId);

    AccessTokenVerificationDto parseAccessToken(String accessToken);
}
