package com.lingyuecm.service;

import com.lingyuecm.common.PagedList;
import com.lingyuecm.dto.BizUserDto;
import com.lingyuecm.dto.CaptchaDto;
import com.lingyuecm.dto.LoginDto;
import com.lingyuecm.model.BizUser;

public interface UserService {
    /**
     * Generates the captcha before logging in
     * @param captchaWidth The desired width of the captcha image
     * @param captchaHeight The desired height of the captcha image
     * @return The captcha generated.
     * @see CaptchaDto
     */
    CaptchaDto generateCaptcha(int captchaWidth, int captchaHeight);

    /**
     * Logs the user in
     * @param user The credentials, including the phone number ({@link BizUser#phoneNo}) and the password ({@link BizUser#loginPwd})
     * @param loginToken The toke generated by {@link #generateCaptcha(int, int)}
     * @param captcha The code displayed on the captcha generated by {@link #generateCaptcha(int, int)}
     * @return The essential information generated for further use
     * @see LoginDto
     */
    LoginDto userLogin(BizUser user, String loginToken, String captcha);

    /**
     * Gets the metadata to display on the web page
     * @return The metadata desired
     * @see BizUserDto
     */
    BizUserDto getMetadata();

    /**
     * Logs the user out
     */
    void userLogout();

    /**
     * Gets the user list on one page
     * @param criteria The criteria for searching
     * @return The data on the page
     * @see BizUserDto
     */
    PagedList<BizUserDto> getUsers(String criteria);
}
