package com.lingyuecm.dto;

import com.lingyuecm.common.LcmWebStatus;
import lombok.Getter;
import lombok.Setter;

/**
 * Detailed information generated by verifying the token, including
 * <li>{@link #webStatus}</li>
 * <li>{@link #userId}</li>
 * <li>{@link #jwtId}</li>
 */
@Setter
@Getter
public class AccessTokenVerificationDto {
    /**
     * The web status indicating the verification result
     */
    private LcmWebStatus webStatus;
    /**
     * The user ID
     */
    private Long userId;
    /**
     * The JWT ID of the token
     */
    private String jwtId;
}
