server:
  port: ${template_port}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: ${db_hikari_max_lifetime}
  data:
    redis:
      password: ${redis_password}
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
# = = = = = = = = = = Customized properties = = = = = = = = = =
bcrypt:
  strength: ${bcrypt_strength} # 4-31
  secret: ${bcrypt_secret}
captcha:
  timeout: ${captcha_timeout}
jwt:
  secrets:
    login-token: ${login_token_secret}
    access-token: ${access_token_secret}
  access-token-timeout: ${access_token_timeout} # The count of milliseconds in which the access token will expire
interceptors:
  token:
    exclusion-patterns: ${token_exclusion}
